accounts/urls.py
from django.urls import path
from .views import RegistrationView, LogInView, LogOutView


app_name = 'accounts'


urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
]

cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove, cart_update_quantity, cart_delete_all

app_name = 'cart'

urlpatterns = [
    path('detail/', cart_detail, name='cart_detail'),
    path('add/<int:id>/', cart_add, name='cart_add'),
    path('remove/<int:id>/', cart_remove, name='cart_remove'),
    path('update_quantity/<int:id>/', cart_update_quantity, name='cart_update_quantity'),
    path('delete_all/', cart_delete_all, name='cart_delete_all'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('', include('accounts.urls', namespace='accounts')),
    path('info/', include('info.urls', namespace='info')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('order/', include('order.urls', namespace='order')),
    path('data/', include('data_processing.urls', namespace='data_processing')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import (OrderCreationView, OrderDetailView, OrderListView, OrderUpdateView, OrderItemInlineView,
                    OrderItemReturnView, InstallmentCreationView)


app_name = 'order'

urlpatterns = [
    path('list/', OrderListView.as_view(), name='order_list'),
    path('creation/', OrderCreationView.as_view(), name='order_creation'),
    path('detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('items/update/<int:pk>/', OrderItemInlineView.as_view(), name='order_items_update'),
    path('items/return/<int:pk>/', OrderItemReturnView.as_view(), name='order_items_return'),
    path('installment/creation/<int:pk>/', InstallmentCreationView.as_view(), name='installment_creation'),
]

cart/models.py
from django.db import models
from django.contrib.auth.backends import get_user_model

from datetime import datetime

from shop.models import Product


User = get_user_model()


class CartModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now)


class CartItem(models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE, related_name='items', null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(default=1)

    def get_cost(self):
        return self.product.get_price() * self.quantity

cart/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from .cart import Cart


def cart_add(request, id):
    Cart(request).add(str(id))
    return redirect('cart:cart_detail')


def cart_remove(request, id):
    Cart(request).remove(str(id))
    return redirect('cart:cart_detail')


def cart_delete_all(request):
    Cart(request).clear()
    return redirect('shop:home')


def cart_update_quantity(request, id):
    quantity = request.GET.get('quantity')
    if not quantity.isnumeric():
        raise ValueError('Invalid Quantity number, it must be numeric')
    Cart(request).add(id, quantity)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    if len(cart) == 0:
        messages.info(request, 'Cart list is empty !! Fill it first to show ')
        return redirect('shop:home')
    return render(request, 'cart/detail.html')

templates/cart/detail.html
{% extends 'base.html' %}
{% load  static %}

{% block content %}
<section class="breadcumb_top_area">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="bread_top_box">
					<h2>Shopping Cart</h2>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="main_cart_area">
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-sm-8 col-xs-12">
				<div class="main_cart_left">
					<div class="cart_heading">
						<div class="h_item1">
							<p>product</p>
						</div>
						<div class="h_item2">
							<p>Price</p>
						</div>
						<div class="h_item3">
							<p>Quantity</p>
						</div>
						<div class="h_item4">
							<p>total</p>
						</div>
					</div>

					{% for item in cart %}
					{% with product=item.product %}
					<div class="cart_item" name="{{product.id}}">
						<div class="cart_item_img">
							<a href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'shop/no_image.png' %}{% endif %}" width="300" height="150" alt="" /></a>
							<p style="margin:3px; padding: 3px; display:inline-block; overflow:hidden; margin-bottom: 0px;">
								<font typeof="bold">
									<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
								</font>
							</p>
						</div>
						<div class="cart_price">
							{% if product.price_sale and product.price_sale < product.price %}
								<p><del> ${{ product.price }}</del></p>  ${{ product.price_sale }}
                    		{% else %}
								<p>${{ product.price }}</p>
                    		{% endif %}
						</div>
						<div class="cart_quantity">
							<p> {{ item.quantity }}</p>
						</div>
						<div class="cart_total">
							<p name="total-{{product.id}}">${{ item.get_cost }}</p>
							<span><a href="{% url 'cart:cart_remove' product.id %}" name="cart_remove" about="{{product.id}}"><i class="fa fa-close"></i></a></span>
						</div>

					</div>
					{% endwith %}
        			{% endfor %}

				</div>
			</div>
			<div class="col-md-3 col-sm-4 col-xs-12">
				<div class="main_cart_right">
					<div class="product_form_total">

						<div class="panel-group" id="home-accordion" role="tablist" aria-multiselectable="true">
							<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="headingTwo">
								<h4 class="panel-title">
								<a class="collapsed" data-toggle="collapse" data-parent="#home-accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
									Cart totals
									<span class="floatright"><i class="fa fa-plus"></i></span>
								</a>
								</h4>
							</div>
							<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
								<div class="panel-body cart_p_body">
								<div class="c_single_item">
									<p>SubTotal</p>
									<span>${{ cart.get_total_price }}</span>
								</div>
								<div class="c_single_item cart_last_total">
									<p>Shipping Charge</p>
									<span>From (10) Up to (40)</span>
								</div>
								<div class="c_total_item sp_single_item">
									<p>Total</p>
									<span>${{ cart.get_total_price }}</span>+(10-40)
								</div>
								</div>
							</div>
							</div>
						</div>
						<input type="submit" value="Proceed to checkout" onclick="window.location='{% if request.user.is_authenticated %}{% url 'order:order_creation' %}{% else %}{% url 'accounts:login' %}{% endif %}';">
					</div>
				</div>
			</div>
		 <a href="{% url 'cart:cart_delete_all' %}" class="delete-cart" name="extra"> delete all cart </a>
		</div>
	</div>
</section>
{% endblock %}