accounts/urls.py
from django.urls import path
from .views import RegistrationView, LogInView, LogOutView


app_name = 'accounts'


urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
]

cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove, cart_update_quantity, cart_delete_all

app_name = 'cart'

urlpatterns = [
    path('detail/', cart_detail, name='cart_detail'),
    path('add/<int:id>/', cart_add, name='cart_add'),
    path('remove/<int:id>/', cart_remove, name='cart_remove'),
    path('update_quantity/<int:id>/', cart_update_quantity, name='cart_update_quantity'),
    path('delete_all/', cart_delete_all, name='cart_delete_all'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('', include('accounts.urls', namespace='accounts')),
    path('info/', include('info.urls', namespace='info')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('order/', include('order.urls', namespace='order')),
    path('data/', include('data_processing.urls', namespace='data_processing')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import (OrderCreationView, OrderDetailView, OrderListView, OrderUpdateView, OrderItemInlineView,
                    OrderItemReturnView, InstallmentCreationView)


app_name = 'order'

urlpatterns = [
    path('list/', OrderListView.as_view(), name='order_list'),
    path('creation/', OrderCreationView.as_view(), name='order_creation'),
    path('detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('items/update/<int:pk>/', OrderItemInlineView.as_view(), name='order_items_update'),
    path('items/return/<int:pk>/', OrderItemReturnView.as_view(), name='order_items_return'),
    path('installment/creation/<int:pk>/', InstallmentCreationView.as_view(), name='installment_creation'),
]

shop/urls.py
from django.urls import path
from .views import HomePage, ProductListView, ProductDetailView, ProductCategoryListView


app_name = 'shop'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_category_list/<int:pk>/', ProductCategoryListView.as_view(), name='product_category_list'),
]

wish/urls.py
from django.urls import path
from .views import wish_detail, wish_add, wish_remove, wish_delete_all


app_name = 'wish'


urlpatterns = [
    path('detail/', wish_detail, name='wish_detail'),
    path('add/<int:id>/', wish_add, name='wish_add'),
    path('remove/<int:id>/', wish_remove, name='wish_remove'),
    path('delete_all/', wish_delete_all, name='wish_delete_all'),
]

templates/base/css.html
{% load static %}

<link rel="shortcut icon" type="image/ico" href="{% static 'images/brand.png' %}"/>
<!-- Font awesome css -->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<!-- Owl carousel css -->
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
<!-- Revolution slider css -->
<link rel="stylesheet" href="{% static 'js/rs-plugin/css/settings.css' %}"/>
<!-- Bootstrap css -->
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<!-- Custom css -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/css/responsive.css' %}">

templates/base/footer.html
<footer class="entire_footer_area">
    <div class="footer_area">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="single_widget">
                        <h5>my account</h5>
                        <div class="wid_line"></div>
                        <ul class="widget_nav">
                            <li><a href="">My Account</a></li>
                            <li><a href="">Personal Information</a></li>
                            <li><a href="">Addresses</a></li>
                            <li><a href="">Discounts</a></li>
                            <li><a href="">Order History</a></li>
                            <li><a href="">Your Vouchers</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="single_widget">
                        <h5>customer service</h5>
                        <div class="wid_line"></div>
                        <ul class="widget_nav">
                            <li><a href="">Help & Contact</a></li>
                            <li><a href="">Shipping & Taxes</a></li>
                            <li><a href="">Return Policy</a></li>
                            <li><a href="">Careers</a></li>
                            <li><a href="">Affliates</a></li>
                            <li><a href="">Legal Notice</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="single_widget">
                        <h5>contact Info</h5>
                        <div class="wid_line"></div>
                        <address>
                            Address : 44 New Design Street,<br>
                            Melbourne 005<br>
                            Phone : (01) 800 433 633<br>
                            Email : info@Example.com
                        </address>
                        <ul class="wid_social">
                            <li><a class="fa fa-facebook" href=""></a></li>
                            <li><a class="fa fa-twitter" href=""></a></li>
                            <li><a class="fa fa-google-plus" href=""></a></li>
                            <li><a class="fa fa-pinterest" href=""></a></li>
                            <li><a class="fa fa-rss" href=""></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_bottom_area">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="footer_bottom">
                        <p>Copyright &copy; 2015 . All Rights Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/base/js.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script>
$(function() {
    $( "#slider-range" ).slider({
      range: true,
      min: 150,
      max: 1500,
      values: [ 520, 1100 ],
      slide: function( event, ui ) {
        $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
      }
    });
    $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
      " - $" + $( "#slider-range" ).slider( "values", 1 ) );
});
</script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.elevatezoom.js' %}"></script>
<script src="{% static 'js/jquery.bxslider.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
 $('.slider8').bxSlider({
    mode: 'vertical',
    slideWidth: 300,
    minSlides: 3,
    slideMargin: 10
  });
 $('.slider9').bxSlider({
    mode: 'vertical',
    slideWidth: 300,
    minSlides: 3,
    slideMargin: 10
  });
 $('.slider10').bxSlider({
    mode: 'vertical',
    slideWidth: 300,
    minSlides: 3,
    slideMargin: 10
  });
});
</script>
<script src="{% static 'js/rs-plugin/js/jquery.themepunch.plugins.min.js' %}"></script>
<script src="{% static 'js/rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script>
<script src="{% static 'js/rs-plugin/rs.home.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!--Opacity & Other IE fix for older browser-->
<!--[if lte IE 8]>
<script type="text/javascript" src="{% static 'js/ie-opacity-polyfill.js' %}"></script>
<![endif]-->
<script src="{% static 'js/main.js' %}"></script>

templates/base/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible"
                 style="{% if forloop.first %}margin-top: 100px;{% endif %}"  role="alert">
                <p>{{ message }}</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/base/nav.html
{% load static %}

<a id="button-to-top"></a>
<div class="outer" id="Clickable"></div>
<div class="loader-mask">
    <div class="loader">
        <div></div>
        <div></div>
    </div>
</div>

<!--Side nav-bar-->
<div id="mySidenav" class="sidenav">
    <div class="toggle-dark-light">
        <input class="container_toggle" type="checkbox" id="switch" name="mode">
        <label for="switch">Toggle</label>
    </div>
    <a href="javascript:void(0)" class="closebtn" id="closeNav">&times;</a>
    <div class="header_top_right login-side-bar visible-xs ">
        <p>
            {% if not request.user.is_authenticated %}
            <a href="{% url 'accounts:login' %}">Login</a>/
            <a class="RegPage" href="{% url 'accounts:registration' %}">Sign up</a>
            {% else %}
            <a class="RegPage" href="{% url 'accounts:logout' %}">Logout</a>
            {% endif %}
        </p>
    </div>
    <div class="info">
        <img src="{% static 'images/comment1.png' %}" alt="User Image" >
        <a href="#">{% if request.user.is_authenticated %} {{ request.user.get_full_name }} {% endif %}</a>
        <a href="#">{% if request.user.is_authenticated %} {{ request.user.username }} {% endif %}</a>
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'order:order_list' %}">Orders</a>
    <a href="category-1.html">Shop</a>
    <a href="contact.html">Contact</a>
    <a href="faqs.html">FAQs</a>
    {% endif %}
</div>

<!--Side nav-bar-->
<section class="nav_area" >
    <div class="contain-nav" id="navbar">
        <div class="container">
            <div class="row" >
                <div class="col-lg-3 col-md-3 col-sm-3 mobile-edit">
                    <div class="header_center">
                        <span id="openNav">&#9776; </span> <a href="{% url 'shop:home' %}"><img src="{% static 'images/brand.png' %}" alt="Site Logo" /></a>
                    </div>
                </div>
                <div class="nav_left col-lg-3 col-md-2 col-sm-2" id="mobo">
                    <a href="{% url 'shop:product_list' %}">category</a>
                    <div class="cat_mega_menu">
                        {% for main_cat in main_categories%}
                        <div class="{% if forloop.counter == 1 %}cat_left{% elif foloop.counter == 2 %}cat_middle{% else %}cat_middle_right{% endif %}">
                            <h5>{{ main_cat.name }}</h5>
                            <div class="cat_menu_line"></div>
                            <ul class="cat_nav">
                                {% for sub_cat in main_cat.sub_categories %}
                                <li><a href="{{ sub_cat.link }}">{{ sub_cat.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endfor %}

                    </div>
                </div>
                <div class="nav_center col-lg-6 col-md-7 col-sm-6">
                    <div class="header_top_right floatright hidden-xs">
                        <p>
                        {% if not request.user.is_authenticated %}
                            <a href="{% url 'accounts:login' %}">Login</a>/
                            <a class="RegPage" href="{% url 'accounts:registration' %}">Sign up</a>
                        {% else %}
                            {% if request.user.is_superuser %} <a class="RegPage" href="{% url 'admin:index' %}">Admin</a>{% endif %}
                            <a class="RegPage" href="{% url 'accounts:logout' %}">Logout</a>
                        {% endif %}</p>
                    </div>
                    <div class="row checkout-mobo">
                        <div class="header_right col-lg-5 col-md-6">
                            <ul class="checkout hidden-sm hidden-xs">
                                <li class="wishlist "><a href="{% url 'wish:wish_detail' %}"><i class="fa fa-heart-o"></i>wishlist</a></li>
                                <li class="mobi_right_li "><a href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>Cart Items</a></li>
                            </ul>
                            <ul	class="checkout visible-sm visible-xs">
                                <li class="wishlist"><a href="cart.html"><i class="fa fa-heart-o"></i></a></li>
                                <li class="mobi_right_li"><a href="checkout.html"><i class="fa fa-shopping-cart"></i></a></li>
                                <li class="find"><span><i class="fa fa-search"></i></span></li>
                                <li class="hidden close-search"><span><i class="fa fa-close"></i></span></li>
                            </ul>
                            <div class="w_likes hidden-sm hidden-xs">
                                <span>{{ wish|length }}</span>
                            </div>
                            <div class="w_likes hidden-sm hidden-xs" style="margin-left:100px;">
                                <span>{{ cart|length }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>