cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove, cart_update_quantity, cart_delete_all

app_name = 'cart'

urlpatterns = [
    path('detail/', cart_detail, name='cart_detail'),
    path('add/<int:id>/', cart_add, name='cart_add'),
    path('remove/<int:id>/', cart_remove, name='cart_remove'),
    path('update_quantity/<int:id>/', cart_update_quantity, name='cart_update_quantity'),
    path('delete_all/', cart_delete_all, name='cart_delete_all'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('', include('accounts.urls', namespace='accounts')),
    path('info/', include('info.urls', namespace='info')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('order/', include('order.urls', namespace='order')),
    path('data/', include('data_processing.urls', namespace='data_processing')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import HomePage, ProductListView, ProductDetailView, ProductCategoryListView


app_name = 'shop'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_category_list/<int:pk>/', ProductCategoryListView.as_view(), name='product_category_list'),
]

wish/urls.py
from django.urls import path
from .views import wish_detail, wish_add, wish_remove, wish_delete_all


app_name = 'wish'


urlpatterns = [
    path('detail/', wish_detail, name='wish_detail'),
    path('add/<int:id>/', wish_add, name='wish_add'),
    path('remove/<int:id>/', wish_remove, name='wish_remove'),
    path('delete_all/', wish_delete_all, name='wish_delete_all'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

from ckeditor.fields import RichTextField

from .managers import ProductManager
from utility_tools.decorators import decimal_limit


class MainCategory(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Main Categories'
        verbose_name_plural = 'Main Categories'


class SubCategory(models.Model):
    name = models.CharField(max_length=120)
    main_category = models.ForeignKey(MainCategory, on_delete=models.SET_NULL, null=True, related_name='sub_categories')

    def get_absolute_url(self):
        return reverse('shop:product_category_list', args=[self.pk])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Sub Categories'
        verbose_name_plural = 'Sub Categories'


class Product(models.Model):
    sub_category = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to="products/")
    short_description = models.CharField(max_length=250, null=True)
    long_description = RichTextField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(1), ])
    price_sale = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, validators=[MinValueValidator(1), ])
    trader_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, validators=[MinValueValidator(1), ])
    stock = models.PositiveIntegerField(validators=[MinValueValidator(1), ])
    sold = models.PositiveIntegerField(null=True, default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProductManager()

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Products'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

    def is_available(self):
        return self.stock > 0 and self.available

    def in_sale(self):
        return bool(self.price_sale)

    def is_new(self):
        return self.get_days_of_creation() < 30

    def clean(self):
        if self.price_sale and self.price_sale > self.price:
            raise ValidationError('Price sale must be less than price')
        if self.trader_price and (self.trader_price > self.price or self.trader_price > self.price_sale):
            raise ValidationError('Trader price should be less than price and sale')

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.pk])

    @decimal_limit
    def sale_percentage(self):
        if self.price_sale and self.price_sale < self.price and self.price_sale != 0:
            return 100*((self.price - self.price_sale)/self.price)
        return 0

    def get_days_of_creation(self):
        return (timezone.now() - self.created).days

    def get_price(self):
        return self.price_sale or self.price


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField()

shop/forms.py
from django import forms

import django_filters as fil

from .models import Product, SubCategory, MainCategory


class ProductFilter(fil.FilterSet):
    name = fil.CharFilter(label='Product Name', field_name="name", lookup_expr="icontains",
                          widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = fil.CharFilter(field_name="short_description", lookup_expr="icontains",
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    main_category = fil.ModelChoiceFilter(field_name='sub_category__main_category', label='Main category',
                                          queryset=MainCategory.objects.all(),
                                          widget=forms.Select(attrs={'class': 'form-control'}))
    category = fil.ModelChoiceFilter(field_name='sub_category', label='Sub category',
                                     queryset=SubCategory.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control'}))
    lower_limit = fil.NumberFilter(field_name="price", lookup_expr="lte",
                                   widget=forms.NumberInput(attrs={'class': 'form-control'}))
    upper_limit = fil.NumberFilter(field_name="price", lookup_expr="gte",
                                   widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Product
        fields = ("name", )

shop/views.py
from django.views.generic import DetailView, ListView, TemplateView

from django_filters.views import FilterView

from .models import Product
from .forms import ProductFilter
from info.models import CarouselImage


class HomePage(TemplateView):
    template_name = 'home.html'
    extra_context = {
        'in_sale_products': Product.objects.in_sale(),
        'recent_products': Product.objects.recent_add(),
        'best_seller_products': Product.objects.best_sales(),
        'carousel_images': CarouselImage.objects.all()
    }


class ProductListView(FilterView):
    model = Product
    filterset_class = ProductFilter
    template_name = 'shop/product_list.html'


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product_obj'
    template_name = 'shop/product_detail.html'

    def get_context_data(self, **kwarg):
        context = super(ProductDetailView, self).get_context_data(**kwarg)
        context.update({'related_products': Product.objects.filter(sub_category=self.object.sub_category)})
        return context


class ProductCategoryListView(ListView):
    model = Product
    template_name = 'shop/product_category_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        return self.model.objects.filter(sub_category__id=self.kwargs.get('pk'))

templates/shop/product_category_list.html
{% extends 'base.html' %}
{% load  static %}

{% block content %}
<section class="main_category_area">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-8 col-xs-12 filter-toggle-main">
                <div class="main_category_right">
                    <div class="row">
                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="main_cat_item">
                                {% for product in products %}
                                <div class="item">
                                    <div class="item-img">
                                        <img style="height: 300px; width: 350px;" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'images/t_item2.jpg' %} {% endif %}" alt="" />
                                        <div class="tr-add-cart">
                                            <ul>
                                                <li><a class="fa fa-shopping-cart tr_cart" href="{% url 'cart:cart_add' product.id %}"></a></li>
                                                <li><a class="tr_text" href="{% url 'cart:cart_add' product.id %}">ADD TO CART</a></li>
                                                <li><a class="fa fa-heart tr_heart" href="{% url 'wish:wish_add' product.id %}"></a></li>
                                                <li><a class="fa fa-search tr_search" href="{{ product.get_absolute_url }}"></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="item-new">
                                        {% if product.is_new %}<p>New</p>{% endif %}
                                        {% if product.in_sale %}<span>-{{ product.sale_percentage }}%</span>{% endif %}
                                    </div>
                                    <div class="item-sub">
                                        <a href="{{ product.get_absolute_url}}"><h5> {{ product.name }}</h5></a>
                                        <p>$ {{ product.get_price }}<span>{% if product.in_sale %}<del>$ {{ product.price }}</del>{% endif %}</span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 pagi-resp">
                            <div class="pagi_line"></div>
                            <div class="pagi_ul">
                                <ul id="pagination">
                                    {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                    {% endif %}
                                    {% for page in page_obj.paginator.page_range %}
                                    <li><a href="?page={{page}}">1</a></li>
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li><a href="">Next</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/shop/product_detail.html
{% extends 'base.html' %}
{% load  static %}

{% block content %}
<!-- Gallery Section -->
<section class="gray_tshirt_area">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="gray_tshirt">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <div class="single_product_image_tab">
                                <div role="tabpanel">
                                    <!-- Nav tabs -->
                                    <ul class="nav nav-tabs product_detail_zoom_tab" role="tablist" id="demo1">
                                        <li role="presentation" class="active">
                                            <a href="#home" aria-controls="main" role="tab" data-toggle="tab">
                                                <div class="small_img">
                                                    <img style="height: 70px; width: 75px;" src="{% if product_obj.image %} {{ product_obj.image.url }} {% else %} {% static 'images/small_img1.jpg' %} {% endif %}" alt="" />
                                                </div>
                                            </a>
                                        </li>
                                        {% for img in product_obj.images.all %}
                                        <li role="presentation">
                                            <a href="#home" aria-controls="img{{ forloop.counter}}" role="tab" data-toggle="tab">
                                                <div class="small_img">
                                                    <img style="height: 70px; width: 75px;" src="{% if img.image %} {{ img.image.url }} {% else %} {% static 'images/small_img1.jpg' %} {% endif %}" alt="" />
                                                </div>
                                            </a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    <!-- Tab panes -->
                                    <div class="tab-content traverse">
                                        <div role="tabpanel" class="tab-pane" id="main">
                                            <div class="single_p_image">
                                                <a href="{% if product_obj.image %} {{ product_obj.image.url }} {% else %} {% static 'images/small_img1.jpg' %} {% endif %}" data-lightbox="image-1" data-title="My caption">
                                                    <img style="height: 560px; width: 650px;" src="images/product-plus.png" alt="" />
                                                </a>
                                                <img style="height: 560px; width: 650px;" id="zoom_01" src="{% if product_obj.image %} {{ product_obj.image.url }} {% else %} {% static 'images/small_img1.jpg' %} {% endif %}" data-zoom-image="images/single-large.jpg" alt=""/>
                                            </div>
                                        </div>
                                        {% for img in product_obj.images.all %}
                                        <div role="tabpanel traverse" class="tab-pane" id="img{{ forloop.counter}}">
                                            <div class="single_p_image">
                                                <a style="height: 560px; width: 650px;" href="{% if img.image %} {{ img.image.url }} {% else %} {% static 'images/small_img1.jpg' %} {% endif %}" data-lightbox="image-1" data-title="My caption"><img src="images/product-plus.png" alt="" /></a>
                                                <img style="height: 560px; width: 650px;" id="zoom_{{ forloop.counter }}" src="{% if img.image %} {{ img.image.url }} {% else %} {% static 'images/small_img1.jpg' %} {% endif %}" data-zoom-image="images/single-large1.png" alt=""/>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <div class="product_detail_heading">
                                <div class="detail_heading_left">
                                    <h3>{{ product_obj.name }}</h3>
                                    <div class="old_price_gray"><p> ${{ product_obj.get_price }} </p></div>
                                    {% if product_obj.in_sale %}<div class="new_price_gray"><del> $ {{ product_obj.price }} </del></div>{% endif %}
                                </div>
                            </div>
                            <div class="panel-group product_accordion" id="home-accordion-single" role="tablist" aria-multiselectable="true">
                                <div class="panel panel-default product_default">
                                    <div class="panel-heading product_accordion_heading" role="tab" id="headingOneP">
                                        <h4 class="panel-title product_accordion_head">
                                            <a data-toggle="collapse" data-parent="#home-accordion-single" href="#collapseOneP" aria-expanded="true" aria-controls="collapseOneP">
                                                Description
                                                <span class="floatright"><i class="fa fa-minus"></i></span>
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseOneP" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOneP">
                                        <div class="panel-body product_ac_body">
                                            <h4>{{ product_obj.short_description }}</h4>
                                            <p>{{ product_obj.long_description|safe }}</p>
                                        </div>
                                    </div>
                                </div>

                                <div class="panel panel-default product_default">
                                    <div class="panel-heading product_accordion_heading" role="tab" id="headingThreeP">
                                        <h4 class="panel-title product_accordion_head">
                                            <a class="collapsed" data-toggle="collapse" data-parent="#home-accordion-single" href="#collapseThreeP" aria-expanded="false" aria-controls="collapseThreeP">
                                                delivery & returns
                                                <span class="floatright"><i class="fa fa-plus"></i></span>
                                            </a>
                                        </h4>
                                    </div>

                                    <div id="collapseThreeP" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThreeP">
                                        <div class="panel-body product_accordion_head">
                                            <div class="single_color">
                                                <div class="color_heading"><h5>Quantity</h5></div>
                                                <div class="color_detail">
                                                    <form action="{% url 'cart:cart_update_quantity' product_obj.id %}">
                                                        <div class="size_down">
                                                            <input type="number" size="4" min="1" class="input-text qty text" title="Qty" value="1" name="quantity" max="119" step="1">
                                                        </div>
                                                        <div class="submit_btn form-group submitRow">
                                                            <input type="submit" name="submit" value="ADD To Cart" />
                                                        </div>
                                                    </form>
                                                    <div class="size_heart">
                                                        <a href="{% url 'wish:wish_add'  product_obj.id %}"><img src="{% static 'images/Product-Details-heart.png' %}" alt="" /></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Related Section -->
<section class="main_category_area product_page_caro">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="main_category_right product-box">
                <h3 class="product">related products</h3>
                <div class="multi_line"></div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div id="owl-example-single" class="owl-carousel">
                              {% for product in related_products%}
                                <div class="item">
                                    <div class="item-img">
                                        <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'images/t_item2.jpg' %} {% endif %}" alt="" />
                                        <div class="tr-add-cart">
                                            <ul>
                                                <li><a class="fa fa-shopping-cart tr_cart" href="{% url 'cart:cart_add' product.id %}"></a></li>
                                                <li><a class="tr_text" href="{% url 'cart:cart_add' product.id %}">ADD TO CART</a></li>
                                                <li><a class="fa fa-heart tr_heart" href="{% url 'wish:wish_add' product.id %}"></a></li>
                                                <li><a class="fa fa-search tr_search" href="{{ product.get_absolute_url}}"></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="item-new">
                                         {% if product.is_new %}<p>New</p>{% endif %}
                                        {% if product.in_sale %}<span>-{{ product.sale_percentage }}%</span>{% endif %}
                                    </div>
                                    <div class="item-sub">
                                        <a href="{{ product.get_absolute_url}}"><h5>{{ product.name }}</h5></a>
                                         <p>$ {{ product.get_price }}<span>{% if product.in_sale %}<del>$ {{ product.price }}</del>{% endif %}</span></p>
                                    </div>
                                </div>
                              {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/shop/product_list.html
{% extends 'base.html' %}
{% load  static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="filter_area">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-8 col-xs-12">
                <div class="filter_box_left">
                    <p>FILTERING:</p>
                    <div class="filter_cont">
                        <ul>
                            <li class="on">on</li>
                            <li><img class="visible" src="images/filter_ico.png" alt=""></li>
                            <li><img class="hidden" src="images/filter_ico_off.png" alt=""></li>
                            <li class="off">off</li>
                        </ul>
                    </div>
                    <div class="s_results">
                        <p><span>|</span> showing 1-12 of 30 results</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="main_category_area">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-4 col-xs-12 filter-toggle">
                <div class="main_category_left">
                    <div class="panel-group" id="home-accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#home-accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Filter
                                        <span class="floatright"><i class="fa fa-minus"></i></span>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                <div class="panel-body">
                                    <form method="GET" style="margin: 20px;">
                                        {{ filter.form }}
                                        <div class="submit_btn form-group submitRow">
                                            <input type="submit" name="submit" value="Submit form" />
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-9 col-sm-8 col-xs-12 filter-toggle-main">
                <div class="main_category_right">
                    <div class="row">
                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="main_cat_item">
                                {% for product in filter.qs %}
                                <div class="item">
                                    <div class="item-img">
                                        <img style="height: 300px; width: 350px;" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'images/t_item2.jpg' %} {% endif %}" alt="" />
                                        <div class="tr-add-cart">
                                            <ul>
                                                <li><a class="fa fa-shopping-cart tr_cart" href="{% url 'cart:cart_add' product.id %}"></a></li>
                                                <li><a class="tr_text" href="{% url 'cart:cart_add' product.id %}">ADD TO CART</a></li>
                                                <li><a class="fa fa-heart tr_heart" href="{% url 'wish:wish_add' product.id %}"></a></li>
                                                <li><a class="fa fa-search tr_search" href="{{ product.get_absolute_url }}"></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="item-new">
                                        {% if product.is_new %}<p>New</p>{% endif %}
                                        {% if product.in_sale %}<span>-{{ product.sale_percentage }}%</span>{% endif %}
                                    </div>
                                    <div class="item-sub">
                                        <a href="{{ product.get_absolute_url}}"><h5> {{ product.name }}</h5></a>
                                        <p>$ {{ product.get_price }}<span>{% if product.in_sale %}<del>$ {{ product.price }}</del>{% endif %}</span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 pagi-resp">
                            <div class="pagi_line"></div>
                            <div class="pagi_ul">
                                <ul id="pagination">
                                    {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                    {% endif %}
                                    {% for page in page_obj.paginator.page_range %}
                                    <li><a href="?page={{page}}">1</a></li>
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li><a href="">Next</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}