cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove, cart_update_quantity, cart_delete_all

app_name = 'cart'

urlpatterns = [
    path('detail/', cart_detail, name='cart_detail'),
    path('add/<int:id>/', cart_add, name='cart_add'),
    path('remove/<int:id>/', cart_remove, name='cart_remove'),
    path('update_quantity/<int:id>/', cart_update_quantity, name='cart_update_quantity'),
    path('delete_all/', cart_delete_all, name='cart_delete_all'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('', include('accounts.urls', namespace='accounts')),
    path('info/', include('info.urls', namespace='info')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('wish/', include('wish.urls', namespace='wish')),
    path('order/', include('order.urls', namespace='order')),
    path('data/', include('data_processing.urls', namespace='data_processing')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import (OrderCreationView, OrderDetailView, OrderListView, OrderUpdateView, OrderItemInlineView,
                    OrderItemReturnView, InstallmentCreationView)


app_name = 'order'

urlpatterns = [
    path('list/', OrderListView.as_view(), name='order_list'),
    path('creation/', OrderCreationView.as_view(), name='order_creation'),
    path('detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('items/update/<int:pk>/', OrderItemInlineView.as_view(), name='order_items_update'),
    path('items/return/<int:pk>/', OrderItemReturnView.as_view(), name='order_items_return'),
    path('installment/creation/<int:pk>/', InstallmentCreationView.as_view(), name='installment_creation'),
]

order/models.py
from decimal import Decimal

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.validators import ValidationError
from django.contrib.auth.backends import get_user_model

from shop.models import Product
from .managers import OrderItemManger


User = get_user_model()


OrderStatus: tuple = (
    ('placed', 'Placed'),
    ('processed', 'Processed'),
    ('shipped', 'Shipped'),
    ('delivered', 'Delivered'),
)

PaymentTypes: tuple = (
    ('cash', 'Cash'),
    ('visa', 'Visa'),
    ('installment', 'Installment')
)

MaxReturnDays: int = 15
RangeReturnDaysDiscount: tuple = 16, 30


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    postal_code = models.CharField(max_length=20, null=True, blank=True)
    location = models.CharField(max_length=150)
    more_description = models.TextField(null=True)

    payment_method = models.CharField(choices=PaymentTypes, max_length=150, null=True)
    status = models.CharField(choices=OrderStatus, max_length=120, null=True, default='placed')

    shipping_charge = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0.00)
    delivered = models.BooleanField(default=False)
    delivered_date = models.DateTimeField(null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def get_all_items(self):
        return self.items.all()

    def get_proper_items(self):
        return self.get_all_items().filter(item_return__isnull=True)

    def get_returned_items(self):
        return self.get_all_items().exclude(self.get_proper_items())

    def get_total_items_cost(self):
        return sum(item.get_total_item_cost() for item in self.get_proper_items())

    def get_total_order_cost(self):
        total = self.get_total_items_cost()
        if self.shipping_charge:
            total += self.shipping_charge
        return total
    get_total_order_cost.short_description = 'Total order cost'

    def get_absolute_url(self):
        return reverse('order:order_detail', args=[self.pk])

    def get_items_url(self):
        return reverse('order:order_items_update', args=[self.pk])

    def available_by_status(self):
        return self.status in ('placed', 'processed')

    def available_by_date(self):
        difference = timezone.now() - self.created
        return difference.days < MaxReturnDays

    def is_delivered(self):
        return self.status == 'delivered'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)

    objects = OrderItemManger()

    def __str__(self):
        return self.product.name

    def get_total_item_cost(self):
        return self.quantity * self.product.get_price()

    def get_product_name(self):
        return self.product.name

    def available_for_return(self):
        return self.order.available_by_date() and self.order.is_delivered()

    def get_status(self):
        if OrderItemReturn.objects.filter(order_item=self):
            return 'returned'
        return self.order.status


class OrderItemReturn(models.Model):
    order_item = models.OneToOneField(OrderItem, on_delete=models.CASCADE, null=True, related_name='item_return')
    extra_fees = models.DecimalField(decimal_places=2, max_digits=10, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.order_item.product.name


class Installment(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE, related_name='installment')
    number_of_months = models.PositiveIntegerField()
    month_pay_amount = models.DecimalField(null=True, decimal_places=4, max_digits=12)

    def get_proper_installment_pay(self):
        return self.installment_pay.all()

    def get_installment_pay_count(self):
        return self.get_proper_installment_pay().count()

    def get_reminder_installment_pay_count(self):
        return self.number_of_months - self.get_installment_pay_count()

    def get_total_installment_pay(self):
        return sum(i.pay_amount for i in self.get_proper_installment_pay())

    def get_total_cost(self):
        return self.number_of_months * self.month_pay_amount


class InstallmentPay(models.Model):
    installment = models.ForeignKey(Installment, on_delete=models.CASCADE, related_name='installment_pay')
    month_number = models.PositiveIntegerField()
    pay_amount = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        if self.pay_amount != self.installment.month_pay_amount:
            raise ValidationError(f'Pay amount is not same as needed: {self.installment.month_pay_amount}')
        super(InstallmentPay, self).save(*args, **kwargs)


@receiver(post_save, sender=OrderItem)
def update_product_stock(sender, instance, created, **kwargs):
    if created:
        quantity = instance.quantity
        product_id = instance.product.id
        Product.objects.filter(id=product_id).update(stock=models.F('stock') - quantity,
                                                     sold=models.F('sold') + quantity)


@receiver(post_save, sender=OrderItemReturn)
def extra_fees_handling(sender, instance, created, **kwargs):
    if created:
        difference = instance.order_item.order.created - instance.date
        price = instance.order_item.product.get_price()
        new_price = price * (15/100) if difference.days in range(*RangeReturnDaysDiscount) else 0
        instance.extra_fees = new_price
        instance.save()

        product_id = instance.order_item.product.id
        quantity = instance.order_item.quantity
        Product.objects.filter(id=product_id).update(stock=models.F('stock') - quantity,
                                                     sold=models.F('sold') + quantity)


@receiver(post_save, sender=Installment)
def interest_rate_handling(sender, instance, created, **kwargs):
    if created:
        one_month_interest_rate = Decimal((20/100) / 12)
        total_months_interest_rate = instance.number_of_months * one_month_interest_rate

        order_cost = instance.order.get_total_items_cost()
        total_interest_rate = order_cost * total_months_interest_rate
        total_order_cost = order_cost + total_interest_rate

        instance.month_pay_amount = total_order_cost / instance.number_of_months
        instance.save()

order/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from utility_tools.forms import BaseModelForm
from .models import Order, OrderItem, OrderItemReturn, Installment


class OrderCreateForm(BaseModelForm):

    class Meta:
        model = Order
        fields = ['payment_method', 'postal_code', 'location', 'more_description']


class OrderItemInlineForm(BaseModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].disabled = True

    class Meta:
        model = OrderItem
        fields = ('product', 'quantity')


class OrderItemReturnInline(BaseModelForm):
    _return = forms.BooleanField(initial=False)

    class Meta:
        model = OrderItemReturn
        fields = ('order_item', )


class InstallmentCreationForm(BaseModelForm):
    readonly_fields = ('order', )

    class Meta:
        model = Installment
        fields = ('order', 'number_of_months')


class OrderItemReturnForm(forms.Form):
    items = forms.ModelMultipleChoiceField(queryset=OrderItem.objects.all(), widget=forms.CheckboxSelectMultiple())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.get('items').queryset = self.initial.get('queryset')


OrderItemInlineFormset = inlineformset_factory(Order, OrderItem, form=OrderItemInlineForm, extra=0)
OrderItemReturnInlineFormset = inlineformset_factory(OrderItem, OrderItemReturn, form=OrderItemReturnInline, extra=0)

order/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import reverse, redirect
from django.views.generic.edit import SingleObjectMixin
from django.views.generic import CreateView, DetailView, UpdateView, ListView, FormView

from cart.cart import Cart
from shop.models import Product
from cart.decorators import CartLenMixIn
from accounts.decorators import UserAuthMixIn
from utility_tools.views import BaseItemInlineView
from .models import Order, OrderItem, OrderItemReturn
from .decorators import OrderOwnerMixIn, OrderEditableMixin, OrderItemsLenMixin, OrderBalanceMixIn
from .forms import OrderCreateForm, InstallmentCreationForm, OrderItemInlineFormset, OrderItemReturnForm


class OrderCreationView(CartLenMixIn, UserAuthMixIn, OrderBalanceMixIn, CreateView):
    model = Order
    form_class = OrderCreateForm
    template_name = 'order/creation.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.object = form.save()
        self.create_order_items()
        if self.object.payment_method == 'installment':
            return redirect('order:installment_creation', self.object.pk)
        return HttpResponseRedirect(self.get_success_url())

    def create_order_items(self):
        cart_order = Cart(self.request)
        cart_content = cart_order.get_cart_content()
        for product_id, quantity in cart_content.items():
            product = Product.objects.filter(id=product_id)
            if not product.exists():
                continue
            product = product.first()
            if product.stock >= quantity:
                OrderItem.objects.create(
                    order=self.object, product=product, quantity=quantity
                )
            else:
                messages.warning(self.request, f"{product.name} has been dropped out of order because of lack of quantity")
        cart_order.clear()
        messages.success(self.request, 'Order has placed successfully')


class OrderDetailView(UserAuthMixIn, OrderOwnerMixIn, OrderItemsLenMixin, DetailView):
    model = Order
    template_name = 'order/detail.html'
    context_object_name = 'order'
    redirect_message = 'Order has no items'


class OrderUpdateView(UserAuthMixIn, OrderOwnerMixIn, OrderEditableMixin, UpdateView):
    model = Order
    form_class = OrderCreateForm
    template_name = 'order/update.html'


class OrderListView(UserAuthMixIn, ListView):
    model = Order
    ordering = ('created', )
    template_name = 'order/list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        queryset = self.model.objects.filter(user=self.request.user)
        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)
        return queryset


class OrderItemInlineView(UserAuthMixIn, OrderOwnerMixIn, OrderEditableMixin, OrderItemsLenMixin, BaseItemInlineView):
    model = Order
    form_class = OrderItemInlineFormset
    template_name = 'order/order_item_inline.html'
    success_message = 'Order items has ben updated successfully'
    context_object_name = 'order_items'
    redirect_message = "Order has no items, all of them were returned"

    def get_success_url(self):
        return reverse('order:order_detail', kwargs={'pk': self.object.pk})


class OrderItemReturnView(UserAuthMixIn, SingleObjectMixin, OrderItemsLenMixin, FormView):

    model = Order
    form_class = OrderItemReturnForm
    template_name = 'order/order_item_return.html'
    success_message = 'Order items has ben removed successfully'
    context_object_name = 'order'
    redirect_message = 'Order has no items to be returned'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('order:order_detail', kwargs={'pk': self.object.pk})

    def get_initial(self):
        cpy = self.initial.copy()
        cpy.update({'queryset': self.object.items.filter(item_return__isnull=True)})
        return cpy

    def form_valid(self, form):
        items = form.cleaned_data.get('items')
        for item in items:
            OrderItemReturn.objects.create(order_item=item)
        return HttpResponseRedirect(self.get_success_url())


class InstallmentCreationView(SingleObjectMixin, OrderOwnerMixIn, FormView):
    model = Order
    form_class = InstallmentCreationForm
    template_name = 'order/installment_creation.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def get_initial(self):
        cpy = self.initial.copy()
        cpy.update({'order': self.object})
        return cpy

    def get_success_url(self):
        return reverse('order:order_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.order = self.object
        self.related_object = form.save()
        return HttpResponseRedirect(self.get_success_url())

templates/order/creation.html
{% extends "base.html" %}
{% block content %}
<style>
    textinput textInput{
		width:450px;
    }
    .breadcumb_top_area .row, .checkout_area .row{
    	float:left
    }
</style>
<body>
<section class="breadcumb_top_area">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="bread_top_box">
					<h2>Checkout</h2>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="checkout_area">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="checkout_left">
					</div>
					<div class="dotted_line"></div>
					<div class="shipping_form">
						<form action="." method="post" class="order-form-creation">
							{{ form.as_p }}
							{% csrf_token %}
						</form>
					</div>
				</div>
			</div>

			<div class="col-md-3 col-sm-4 col-xs-12" style="margin-left: 470px;">
				<div class="checkout_right">
					<h4>Review of Your Order</h4>

					<div class="product_form_total">
						<div class="c_main_item">
							<p>Product</p>
							<span>Total</span>
						</div>

					 {% for i in cart %}
						<div class="c_single_item">
							<p>{{ i.product.name }}</p>
							<span>${{ i.get_cost }}</span>
						</div>
					  {% endfor %}

						<div class="c_total_item sp_single_item">
							<p>Order Total</p>
							<span>$${{ cart.get_total_price }}</span>
						</div>

						<div class="checkbox">
							<label>
							  <input type="checkbox"> I have Read & Accept <span>Terms & Conditions</span>
							</label>
						</div>
						<input type="submit" value="Place order now"/>
					</div>
				</div>
			</div>
		</div>
</section>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script>
	$('input[value="Place order now"]').click(function (){
		$(".order-form-creation").submit()
	})
</script>
{% endblock %}

templates/order/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="breadcumb_top_area">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="bread_top_box">
					<h2>Order Detail</h2>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="main_cart_area">
	<div class="container">
		<div class="row">

            <div class="col-md-9 col-sm-8 col-xs-12">
				<div class="main_cart_left">
					<div class="cart_heading">
						<div class="h_item1">
							<p>product</p>
						</div>
						<div class="h_item2">
							<p>Price</p>
						</div>
						<div class="h_item3">
							<p>Quantity</p>
						</div>
						<div class="h_item4">
							<p>total</p>
						</div>
					</div>
					{% for item in order.get_proper_items %}
					{% with product=item.product %}
					<div class="cart_item" name="{{product.id}}">
						<div class="cart_item_img">
							<a href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'shop/no_image.png' %}{% endif %}" width="300" height="150" alt="" /></a>
							<p style="margin:3px; padding: 3px; display:inline-block; overflow:hidden; margin-bottom: 0px;">
								<font typeof="bold">
									<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
								</font>
							</p>
						</div>
						<div class="cart_price">
							{% if product.price_sale and product.price_sale < product.price %}
								<p><del> ${{ product.price }}</del></p>  ${{ product.price_sale }}
                    		{% else %}
								<p>${{ product.price }}</p>
                    		{% endif %}
						</div>
						<div class="cart_quantity">
							<p> {{ item.quantity }}</p>
						</div>
						<div class="cart_total">
							<p name="total-{{product.id}}">${{ item.get_cost }}</p>
						</div>
					</div>
					{% endwith %}
        			{% endfor %}
				</div>
			</div>

			<div class="col-md-3 col-sm-4 col-xs-12">
				<div class="main_cart_right">
					<div class="product_form_total">
						<div class="panel-group" id="home-accordion" role="tablist" aria-multiselectable="true">
							<div class="panel panel-default">
							<div class="panel-heading" role="tab" id="headingTwo">
								<h4 class="panel-title">
								<a class="collapsed" data-toggle="collapse" data-parent="#home-accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
									Order totals
									<span class="floatright"><i class="fa fa-plus"></i></span>
								</a>
								</h4>
							</div>
							<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
								<div class="panel-body cart_p_body">
								<div class="c_single_item">
									<p>SubTotal</p>
									<span>${{ order.get_total_items_cost }}</span>
								</div>
								<div class="c_single_item cart_last_total">
									<p>Shipping Charge</p>
									<span>From (10) Up to (40)</span>
								</div>
								<div class="c_total_item sp_single_item">
									<p>Total</p>
									<span>${{ order.get_total_order_cost }}</span>+(10-40)
								</div>
								</div>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
		<div class="row">

			<div class="col-md-9 col-sm-8 col-xs-12">
				<div class="main_cart_left">
					{% if order.installment %}
					<h4> Installment Details </h4>
					{% with isnt=order.installment %}
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col">Number Of Months</th>
								<th scope="col">Pay Amount / Month </th>
								<th scope="col">Number Of Months Payed</th>
								<th scope="col">Total Payed</th>
								<th scope="col">Total Cost</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">{{ isnt.number_of_months }}</th>
								<td>{{ isnt.month_pay_amount }}</td>
								<td>{{ isnt.get_installment_pay_count }}</td>
								<td>{{ isnt.get_total_installment_pay }}</td>
								<td>{{ isnt.get_total_cost }}</td>
							</tr>
						  </tbody>
					</table>
					{% endwith %}
					{% endif %}
				</div>

			</div>
		</div>

	</div>
</section>
{% endblock %}

templates/order/installment_creation.html
{% extends "base.html" %}

{% block content %}
<section class="breadcumb_top_area">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="bread_top_box">
					<h2>Installment</h2>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="checkout_area">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="checkout_left"></div>
                <div class="dotted_line"></div>
                <div class="shipping_form">
                    <form action="." method="post" class="order-form-creation">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <input type="submit" value="Save"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/order/list.html
{% extends "base.html" %}

{% block content %}
<table class="table table-striped" style="width:85%; align:center; margin: 0 auto; margin-top:35px;">
    <thead>
    <tr>
        <th scope="col">N</th>
        <th scope="col">Postal Code</th>
        <th scope="col">Location</th>
        <th scope="col">Payment</th>
        <th scope="col">Status</th>
        <th scope="col">Total</th>
        <th scope="col">Shipping Charge</th>
        <th scope="col">Delivered</th>
        <th scope="col">Delivered Date</th>
        <th scope="col">Created</th>
        <th scope="col">Updated</th>
        <th scope="col">Detail</th>
        <th scope="col">Edit</th>
        <th scope="col">Return</th>
    </tr>
    </thead>
    <tbody>
    {% for order in orders %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ order.postal_code }}</td>
        <td>{{ order.location }}</td>
        <td>{{ order.payment_method }}</td>
        <td>{{ order.status }}</td>
        <td>{{ order.get_total_order_cost }}</td>
        <td>{{ order.shipping_charge }}</td>
        <td>{{ order.delivered }}</td>
        <td>{% if order.delivered_date %} {{ order.delivered_date }} {% else %} - {% endif %}</td>
        <td>{{ order.created }}</td>
        <td>{{ order.updated }}</td>
        <td><a href="{{ order.get_absolute_url }}">more</a></td>
        <td><a href="{{ order.get_items_url }}">edit</a></td>
        <td><a href="{% url 'order:order_items_return' order.id %}">more</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/order/order_item_inline.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post" enctype="multipart/form-data" style="width:80%; align:center; margin: 0 auto; margin-top: 20px;">
    {% csrf_token %}
    {{ form.management_form }}
    {{ form.non_form_errors.as_ul }}
    <table id="formset" class="form">
        {% for single_form in form.forms %}
        {% if forloop.first %}
        <thead>
            <tr>
                {% for field in single_form.visible_fields %}
                <th>{{ field.label|capfirst }}</th>
                {% endfor %}
            </tr>
        </thead>
        {% endif %}
        <tr class="{% cycle row1 row2 %}">
            {% for field in single_form.visible_fields %}
            <td>
                {% if forloop.first %}
                    {% for hidden in single_form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                {% endif %}
                {{ field.errors.as_ul }}
                {{ field }}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <br>
    <button type="submit" class="btn btn-dark btn-lg " style="align:center; margin: 0 auto; margin-left: 270px; margin-top:20px;">Save </button>
</form>
{% endblock %}

templates/order/order_item_return.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST" class="contact-form" style="width:65%; align:center; margin: 0 auto; margin-top:35px">
   <h4 style="text-align:center;"> Return Order Products </h4>
   {% csrf_token %}
   {{ form.as_p }}
   <div class="d-grid" style="margin-top:10px;"><button class="btn btn-dark btn-lg" type="submit">Return</button></div>
</form>
{% endblock %}

templates/order/update.html
{% extends "base.html" %}

{% block content %}
<section class="breadcumb_top_area">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="bread_top_box">
					<h2>Update Order</h2>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="checkout_area">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="checkout_left"></div>
                <div class="dotted_line"></div>
                <div class="shipping_form">
                    <form action="." method="post" class="order-form-creation">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <input type="submit" value="Update Order"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}